apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-hook-1
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install
        image: hub.kce.ksyun.com/dmetasoul/wait_for:latest
        imagePullPolicy: IfNotPresent
        command: ["/wait_dependency.sh"]
        args: ["wait_for", "certmanager:CERTMANAGER_URL"]
        env:
          - name: CERTMANAGER_URL
            value: cert-manager-webhook.cert-manager.svc
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1