{{- if ".Values.secrets-web-app.enabled" }}
{{- include "prechecks" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-service-account
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: secrets-web-app-kubeflow-volume-ui-admin
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: secrets-web-app-kubeflow-volume-ui-edit
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: secrets-web-app-kubeflow-volume-ui-view
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-web-app-cluster-role
subjects:
- kind: ServiceAccount
  name: secrets-web-app-service-account
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
data:
  SWA_CLUSTER_DOMAIN: cluster.local
  SWA_PREFIX: /secrets
  SWA_USERID_HEADER: kubeflow-userid
  SWA_USERID_PREFIX: ""
  SWA_SECURE_COOKIES: "False"
kind: ConfigMap
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-parameters-7k4fhhkmdc
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
    run: secrets-web-app
  name: secrets-web-app-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-web-app
      kustomize.component: secrets-web-app
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: secrets-web-app
        kustomize.component: secrets-web-app
    spec:
      containers:
      - env:
        - name: APP_PREFIX
          value: /secrets
        - name: USERID_HEADER
          value: kubeflow-userid
        - name: USERID_PREFIX
          value: ""
        - name: APP_SECURE_COOKIES
          value: $(SWA_SECURE_COOKIES)
        image: {{ .Values.secretsWebAppImage }}
        imagePullPolicy: Always
        name: secrets-web-app
        ports:
        - containerPort: 5000
      serviceAccountName: secrets-web-app-service-account
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: secrets-web-app
    kustomize.component: secrets-web-app
  name: secrets-web-app-secrets-web-app
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /secrets
    match:
    - uri:
        prefix: /secrets/
    rewrite:
      uri: /
    route:
    - destination:
        host: secrets-web-app-service.kubeflow.svc.cluster.local
        port:
          number: 80
{{- end }}